version: '3'
services:
  database:
    image: mysql:5.7
    volumes:
      - ${PWD}/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: imagini
      MYSQL_ROOT_PASSWORD: secret
  service:
    build: .
    volumes:
      - ${PWD}/settings.json:/opt/app/settings.json
    ports:
      - '3000:3000'
    restart: on-failure
